### ISSUE TITLE
Use '-noverify' JVM arg instead of '-XX:-UseSplitVerifier' with Java8

### ISSUE THREAD

**Issue by gslowikowski** [play1-maven-plugin/play1-maven-plugin#156]
This argument is added to Java command line when forking JVM in: `run`, `test`, `start` and `precompile` mojos.

Pull request https://github.com/play1-maven-plugin/play1-maven-plugin/pull/155 was already prepared.

It reflects the changes in Play:
- https://github.com/playframework/play1/commit/767f09f30763dd607c509f38e84f2c0aabdaa66c
Support Java 8. (Using "-noverify" option instead of "-XX:-UseSplitVerifier" - it works with both Java7 and Java8)
- playframework/play1#748 (https://github.com/playframework/play1/commit/8f5e3e591baf50cbfda11722cd4195957c598d14, https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1800-support-java-8)
- https://github.com/playframework/play1/commit/b47f99f02a139f3b2980dd43a667df73c52ee7bc Refactor getJavaVersion (https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1871-play-java-version-detection-is-not-correct)

Some additional Oracle docs:
- http://www.oracle.com/technetwork/java/javase/compatibility-417013.html [section about JSR 202]
- http://stackoverflow.com/questions/15253173/how-safe-is-it-to-use-xx-usesplitverifier
- https://community.oracle.com/blogs/fabriziogiudici/2012/05/07/understanding-subtle-new-behaviours-jdk-7

**Comment by gslowikowski** [comment]
Pull request #155 was already merged. New `1.0.0-beta8-SNAPSHOT` snapshot deployed.

@Neoh59, do you want to be added as a first contributor in `pom.xml` file?

**Comment by Neoh59** [comment]
No need to add me as a contributor. It's "a drop in the ocean" in comparison to the work you did :-)

But feel free to do that if you want.

**Comment by gslowikowski** [comment]
New `1.0.0-beta8-SNAPSHOT` of `play-app-default-parent` deployed.
